ENCODER_MAP_ENABLE = yes
VIA_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes
WPM_ENABLE = no
VELOCIKEY_ENABLE = no
TAP_DANCE_ENABLE = no
SPACE_CADET_ENABLE = no
CONSOLE_ENABLE = no
AUDIO_ENABLE   = no
DYNAMIC_MACRO_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = no
AUTO_SHIFT_ENABLE = no
KEY_LOCK_ENABLE = yes
OPT_DEFS += -DDYNAMIC_KEYMAP_LAYER_COUNT=5

# Bootloader selection
BOOTLOADER = stm32-dfu
