#include "custom_rgb_effect.h"
#include "custom_rgb_layers.h"
#include "custom_rgb_effect_2.h"
#include "custom_rgb_reactive.h"
#include "custom_rgb_coordinate.h"
#include "custom_rgb_zones.h"


// RGB_MATRIX_EFFECT(custom_rgb_effect)

// #ifdef RGB_MATRIX_CUSTOM_EFFECT_IMPLS


// static bool custom_rgb_effect(effect_params_t *params){
//     RGB_MATRIX_USE_LIMITS(led_min, led_max);
//     return rgb_matrix_check_finished_leds(led_max);
// }

// #endif

